### ISSUE TITLE
Call for papers

### ISSUE THREAD

**Issue by pedromazala** [bemugmga/meetups#1]
# 2º Encontro - Backend Meetup Group (Bemugo)
#### Nome
Darth Vader
#### Twitter
@anakin_skywalker
#### Grau da palestra
- [ ] Iniciante
- [x] Intermediário
- [ ] Avançado
#### Abstract
Luke, help me take this mask off. But you'll die. Nothing can stop that now. Just for once... let me look on you with my own eyes. Now...go, my son. Leave me. No. You're coming with me. I can't leave you here. I've got to save you. You already have, Luke. You were right about me. Tell your sister...you were right. Father...I won't leave you. There it is! All right, Wedge. Go for the power regulator on the north tower. Copy, Gold Leader. I'm already on my way out. Move the fleet away from the Death Star. 
Generated by [Forcem Ipsum](http://forcemipsum.com/#)

----

## Code

Aqui está o código markdown desta issue:
```
# BEMUGO

## {Aqui vai o título da sua palestra. PS: colocar o mesmo nome no título da issue}

#### Nome
Darth Vader
#### Twitter
@anakin_skywalker
#### Grau da palestra
- [ ] Iniciante
- [x] Intermediário
- [ ] Avançado
#### Abstract
Luke, help me take this mask off. But you'll die. Nothing can stop that now. Just for once... let me look on you with my own eyes. Now...go, my son. Leave me. No. You're coming with me. I can't leave you here. I've got to save you. You already have, Luke. You were right about me. Tell your sister...you were right. Father...I won't leave you. There it is! All right, Wedge. Go for the power regulator on the north tower. Copy, Gold Leader. I'm already on my way out. Move the fleet away from the Death Star. 
Generated by [Forcem Ipsum](http://forcemipsum.com/#)

----

## Votação
Para tornar a votação democrática as palestras aqui submetidas com mais :+1:  serão escolhidas para o encontro, porém fica o convite para que você submeta também nos próximos encontros.
```
----

## Votação
Para tornar a votação democrática as palestras aqui submetidas com mais :+1:  serão escolhidas para o encontro, porém fica o convite para que você submeta também nos próximos encontros.

**Comment by rhnonose** [comment]
# BEMUGO

## CQRS e ES: saindo da rotina

#### Nome
Rodrigo Nonose
#### Twitter
@RodrigoNonose
#### Grau da palestra
- [ ] Iniciante
- [x] Intermediário
- [x] Avançado
#### Abstract
CQRS (Command-Query Responsibility Segregation) e ES (Event Sourcing) são conceitos para se modelar sistemas de uma maneira diferente das tradicionais de registro/tabela/documento/arquivo. Nessa palestra, vou dar uma introdução sobre esses conceitos em como/quando/onde/por que usá-los e os trade-offs resultantes.

**Comment by pedromazala** [comment]
# BEMUGO

## TDD - O que é? Onde vive? Hoje no Bemugo Repórter.

#### Nome
Pedro Mázala
#### Grau da palestra
- [x] Iniciante
- [x] Intermediário
- [ ] Avançado
#### Abstract
TDD é um conceito muito conversado, porém muito pouco aplicado. A ideia do encontro é dar um overview do que é, como trabalhar e destinar um tempinho para fazermos um code DOJO utilizando TDD.
#### Expectativa de duração
1:30h

------------------------

PS: Além de votar com :+1:, coloque um :heart: para o DOJO ser em PHP e :smile: para ser em JS

**Comment by rhnonose** [comment]
@pedromazala o 😆 não aparece como reaction 😉

**Comment by pedromazala** [comment]
@rhnonose mudei... HAHA esses negócios de front n dá pra mim... HAHAHAH zueira
