### ISSUE TITLE
10º Backend Meetup Group MGA - Submeta/Vote seu tema

### ISSUE THREAD

**Issue by wwwflorencio** [bemugmga/meetups#10]
Dessa vez faremos algo diferente, já temos [uma palestra confirmada](https://github.com/bemugmga/meetups/issues/9#issuecomment-392883065) e após essa palestra inciaremos uma mesa redonda para discussão o/

Para isso precisamos de sugestões de temas. Vamos fazer isso no seguinte modelo:
- Comente nessa issue o tema que você quer seguindo o [modelo do primeiro comentário](https://github.com/bemugmga/meetups/issues/10#issuecomment-398188873)
- Vote com 👍 o tema que quer discutir no dia

Até lá galera, link com local em breve.

**Comment by wwwflorencio** [comment]
Sugestão de tema: Como colaborar na comunidade local e open source.

**Comment by rhnonose** [comment]
Sugestão de tema: Como escolher sua tech-stack

**Comment by rhnonose** [comment]
Sugestão de tema: salário dev

**Comment by geovanisouza92** [comment]
Sugestão de tema: O problema que você resolve é mais importante que o código que você escreve.

Um resumo [deste artigo](https://levelup.gitconnected.com/the-problem-you-solve-is-more-important-than-the-code-you-write-d0e5493132c6) propondo uma discussão e reflexão sobre o que realmente importa.

**Comment by wellington1993** [comment]
Sugestão de tema: Como acompanhar novas tecnologias e como se manter atualizado e competitivo no mercado de trabalho
