### ISSUE TITLE
11º Backend Meetup Group MGA

### ISSUE THREAD

**Issue by rhnonose** [bemugmga/meetups#11]
## 11º Backend Meetup Group MGA
Estamos indo para o décimo primeiro encontro do BEMUGMGA. Vai rolar dia *02/08* a partir das *19h* (vai cair em uma quinta feira).

Contamos com sua participação :D

Será uma palestra e discussão no estilo [fishbowl](agiletrendsbr.com/fishbowls/). Submeta sua palestra/sugestão de discussão no formato abaixo:

## Palestra
Para submeter palestras comente nessa issue seguindo o modelo da issue #2 
## Discussão
Para sugerir temas, especifique que é uma sugestão de tema e faça sua sugestão. Exemplo:
#### {a sua sugestão}

Para tornar a votação democrática, as palestras/sugestões submetidas com mais 👍 serão escolhidas para o encontro.
Mesmo que a sua palestra/sugestão não for escolhida, fica o convite para que você submeta também nos próximos encontros.

**Comment by porcelani** [comment]
Sugestão de tema: Como fazer todos definitivamente entenderem o que DevOps realmente é?

**Comment by netstart** [comment]
Sugestão de tema: Utilizando Vert.x na implementação de microserviços

**Comment by netstart** [comment]
Sugestão de tema: Utilizando Spring webflux na implementação de microserviços

**Comment by dotenorio** [comment]
## Software Livre: chegou a sua hora de contribuir!

#### Nome
Fernando Migliorini Tenório

#### Grau da palestra
- [X] Iniciante

#### Tempo previsto
00:30h
#### Abstract
Bom, usamos os famosos software, bibliotecas, posts, etc.. livres todos os dias o tempo todo, mas será que devolvemos algo para comunidade?? Talvez já tenha passado a hora de você contribuir de alguma forma..

Acredite!

Um simples ponto pode deixar o dono do repositório imensamente grato.

**Comment by juliovedovatto** [comment]
Sugestão de tema: discussão sobre REST e GraphQL

https://blog.goodapi.co/rest-vs-graphql-a-critical-review-5f77392658e7

**Comment by vrufine** [comment]
## GraphQL vs REST: Por que GraphQL é melhor que REST?

#### Nome

Vinícius Rufine

#### Grau da palestra

- [x] Iniciante

#### Tempo previsto

00h 30min

#### Abstract

Nessa talk irei falar um pouco da minha experiência com GraphQL, mostrar alguns códigos de aplicações que estão em produção, fornecendo e consumindo, APIs utilizando essa tecnologia e assim, comprovando que GraphQL>REST

**Comment by rhnonose** [comment]
https://www.meetup.com/developerparana/events/253306850/
