### ISSUE TITLE
12º Backend Meetup Group MGA

### ISSUE THREAD

**Issue by rhnonose** [bemugmga/meetups#12]
## 12º Backend Meetup Group MGA
Estamos indo para o décimo primeiro encontro do BEMUGMGA. Vai rolar dia *23/08* a partir das *19h* (vai cair em uma quinta feira).

Contamos com sua participação :D

Será uma palestra e discussão no estilo [fishbowl](agiletrendsbr.com/fishbowls/). Submeta sua palestra/sugestão de discussão no formato abaixo:

## Palestra
Para submeter palestras comente nessa issue seguindo o modelo da issue #2 
## Discussão
Para sugerir temas, especifique que é uma sugestão de tema e faça sua sugestão. Exemplo:
#### {a sua sugestão}

Para tornar a votação democrática, as palestras/sugestões submetidas com mais 👍 serão escolhidas para o encontro.
Mesmo que a sua palestra/sugestão não for escolhida, fica o convite para que você submeta também nos próximos encontros.

**Comment by juliovedovatto** [comment]
**Sugestão de tema**

Trabalhando Serverless

**Comment by rhnonose** [comment]
#### Sugestão de tema

A melhor linguagem de programação

**Comment by wwwflorencio** [comment]
## Construindo um serviço de telemetria usando AWS

#### Nome
Marcos Florencio

#### Grau da palestra
- [ ] Iniciante
- [x] Intermediário
- [ ] Avançado

#### Tempo previsto
30m

#### Abstract
Um papo sobre a construção de um serviço de monitoramento de milhões de ações por dia de usuários, usuários de usuários, usuários de usuários de usuários de usuários. Pedras no caminhos, tapas na cara, sustos entre outros.
