### ISSUE TITLE
3º Encontro - Backend Meetup Group (Bemugo)

### ISSUE THREAD

**Issue by pedromazala** [bemugmga/meetups#3]
# 3º Encontro - Backend Meetup Group (Bemugo)
## Data a definir (provavelmente quinta, 09 de março de 2018 19:00)
------
## Votação
Para tornar a votação democrática as palestras aqui submetidas com mais :+1:  serão escolhidas para o encontro, porém fica o convite para que você submeta também nos próximos encontros.

Para submeter palestras comente nessa issue seguindo o modelo da issue #2

**Comment by rhnonose** [comment]
## Orientação a Objetos ou Funcional

#### Nome
Rodrigo Nonose
#### Grau da palestra
- [x] Iniciante
- [x] Intermediário
- [ ] Avançado
#### Tempo previsto
30:00
#### Abstract
Paradigma de programação é algo que, como dev, temos contato o tempo todo quando tocamos em código. Querendo ou não, um código possui um paradigma de programação, ditados pela linguagem/framework/editor de texto/IDE/cultura em uma cominação, hora elegante, hora bizarra.
Nesta palestra, pretendo ilustrar a diferença prática entre os paradigmas de orientação a objeto e funcional, motivos pelos quais o paradigma funcional está entrando com força e por que você deveria questionar como você escreve código atualmente.

**Comment by lucassmacedo** [comment]
## Laravel QuickStart - Introdução ao Framework

#### Lucas Macedo
- [x] Iniciante
- [ ] Intermediário
- [ ] Avançado
#### Tempo previsto
01:00h
#### Abstract
A idéia da Talk é apresentar os conceitos básicos do Laravel, mostrando as principais funcionalidades e as vantagens que o framework proporcional.
