### ISSUE TITLE
4º  Backend Meetup Group MGA - Aceleradora Orbital #C4P

### ISSUE THREAD

**Issue by wwwflorencio** [bemugmga/meetups#4]
# 4º  Backend Meetup Group MGA - Aceleradora Orbital #C4P

Estamos indo para o quarto encontro do BEMUGMGA, e dessa vez vai rolar na Aceleradora Orbital no dia **20/03 à partir das 19h** (vai cair em uma terça feira).

Contamos com sua participação :D

Meetup:
https://www.meetup.com/pt-BR/developerparana/events/248627058/

## Votação
Para tornar a votação democrática as palestras aqui submetidas com mais +1 serão escolhidas para o encontro, porém fica o convite para que você submeta também nos próximos encontros.

Para submeter palestras comente nessa issue seguindo o modelo da issue #2

**Comment by dotenorio** [comment]
## [Expressões Regulares] Uma abordagem divertida

#### Nome
Fernando Tenório
#### Grau da palestra
- [x] Iniciante
- [ ] Intermediário
- [ ] Avançado
#### Tempo previsto
01:00h
#### Abstract
Nesta palestra pretendo trazer o significado de cada metacaractere que compõe uma expressão regular. E se tudo der certo, alguns exemplos práticos 😀.

**Comment by pedromazala** [comment]
## CI: O que essa sigla tão falada significa? Como fazer?

#### Nome
Pedro Mázala
#### Grau da palestra
- [ ] Iniciante
- [x] Intermediário
- [ ] Avançado
#### Tempo previsto
01:00h
#### Abstract
Uma abordagem prática sobre como aplicar CI no seu código utilizando Jenkins e testes unitários
