### ISSUE TITLE
5º Backend Meetup Group MGA - Accion #C4P

### ISSUE THREAD

**Issue by wwwflorencio** [bemugmga/meetups#5]
# 5º  Backend Meetup Group MGA - Accion #C4P

Estamos indo para o quinto encontro do BEMUGMGA, e dessa vez vai rolar na Accion no dia **05/04** à partir das **19h** (vai cair em uma quinta feira).

Contamos com sua participação :D

Inscrições gratuitas:
https://www.meetup.com/pt-BR/developerparana/events/248957512/

## Votação
Para tornar a votação democrática as palestras aqui submetidas com mais :+1: serão escolhidas para o encontro, porém fica o convite para que você submeta também nos próximos encontros.

Para submeter palestras comente nessa issue seguindo o modelo da issue #2

**Comment by ezidio** [comment]
## Testes com Spring Boot de forma fácil!

#### Nome
Everton Emilio Tavares
#### Grau da palestra
- [ ] Iniciante
- [x] Intermediário
- [ ] Avançado
#### Tempo previsto
1:00
#### Abstract

Em se tratando de testes, alguns pontos que parecem complexos como popular uma tabela para testes, ou subir uma API para testar o endpoint é simples se conhecido os atalhos que as ferramentas oferecem;
O objetivo desta palestra é mostrar como testar partes da aplicação Spring de forma fácil e rápida, utilizando os mecanismos que o framework oferece!

----

**Comment by rhnonose** [comment]
## Microserviços: como dar um tiro no próprio pé

#### Nome
Rodrigo Nonose
#### Grau da palestra
- [ ] Iniciante
- [x] Intermediário
- [x] Avançado
#### Tempo previsto
1:00h
#### Abstract
Essa palestra tem como objetivo mostrar os riscos de se abusar dos conceitos de microserviços, por que não usá-los, quando **talvez** usá-los e ter ciência dos trade-offs.

**Comment by gumieri** [comment]
## Serverless & Serverless Framework

#### Nome
Rafael Gumieri
#### Grau da palestra
{Marque com um X o nível da palestra}
- [x] Iniciante
- [x] Intermediário
- [ ] Avançado
#### Tempo previsto
1:00h
#### Abstract
O que "serverless" tem a nos oferecer e quando não se deve utilizar. Também quais as características dos serviços de "funções" disponíveis no mercado, as ferramentas que existem hoje para facilitar o desenvolvimento de aplicações serverless e principalmente: como instalar, configurar e utilizar o "Serverless Framework".
