### ISSUE TITLE
6º Backend Meetup Group MGA - Orbital #C4P

### ISSUE THREAD

**Issue by pedromazala** [bemugmga/meetups#6]
# 6º  Backend Meetup Group MGA - Orbital #C4P

Estamos indo para o sexto encontro do BEMUGMGA. Nós estamos aguardando o local para realização do evento. Vai rolar dia **24/04** à partir das **19h** (vai cair em uma quinta feira).

Contamos com sua participação :D

**Link meetup** https://www.meetup.com/pt-BR/developerparana/events/249579018/

## Votação
Para tornar a votação democrática as palestras aqui submetidas com mais :+1: serão escolhidas para o encontro, porém fica o convite para que você submeta também nos próximos encontros.

Para submeter palestras comente nessa issue seguindo o modelo da issue #2

**Comment by pedromazala** [comment]
## Não seja um NPC no desenvolvimento

#### Nome
Pedro Mázala
#### Grau da palestra
- [x] Iniciante
- [ ] Intermediário
- [ ] Avançado
#### Tempo previsto
01:00h
#### Abstract
Ser um NPC e ter várias pessoas iguais a você não é legal em lugar nenhum. Nessa palestra vamos falar sobre como é possível tirar os pesos e voar como um `Boss Developer` 😄 

Vamos trocar ideias sobre o que é interessante de ser feito e onde você deve focar seus esforços para ser um `Boss Developer`

**See you later, alligator!**


----

**Comment by rhnonose** [comment]
## Microserviços: como dar um tiro no próprio pé

#### Nome
Rodrigo Nonose
#### Grau da palestra
- [ ] Iniciante
- [x] Intermediário
- [x] Avançado
#### Tempo previsto
1:00h
#### Abstract
Essa palestra tem como objetivo mostrar os riscos de se abusar dos conceitos de microserviços, por que não usá-los, quando **talvez** usá-los e ter ciência dos trade-offs.
