### ISSUE TITLE
7º Backend Meetup Group MGA - DB1 Global Software

### ISSUE THREAD

**Issue by wwwflorencio** [bemugmga/meetups#7]
# 7º  Backend Meetup Group MGA - DB1 Global Software

Estamos indo para o sétimo encontro do BEMUGMGA. Vai rolar dia **10/05** à partir das **19h** (vai cair em uma quinta feira).

Contamos com sua participação :D

**Link meetup** https://www.meetup.com/pt-BR/developerparana/events/250133057/

## Votação
Para tornar a votação democrática as palestras aqui submetidas com mais :+1: serão escolhidas para o encontro, porém fica o convite para que você submeta também nos próximos encontros.

Para submeter palestras comente nessa issue seguindo o modelo da issue #2

**Comment by juliovedovatto** [comment]
## Node JS vs PHP para desenvolvimento Server-Side

#### Nome
Julio Vedovatto

#### Grau da palestra

- [x] Iniciante
- [x] Intermediário
- [ ] Avançado

#### Tempo previsto
00:40h

#### Abstract

Um clássico X vs Y, uma abordagem rápida sobre NodeJS e PHP para desenvolvimento server-side (backend).

**Comment by dotenorio** [comment]
## Electron: aplicações multiplataforma com JavaScript, HTML e CSS

#### Nome
Fernando Migliorini Tenório

#### Grau da palestra
- [ ] Iniciante
- [x] Intermediário
- [ ] Avançado

#### Tempo previsto
00:45h

#### Abstract
Vamos descobrir como construir aplicativos desktop multiplataforma com JavaScript, HTML e CSS e se isso é realmente tão bom quanto parece ser.
