### ISSUE TITLE
8º Backend Meetup Group MGA - Tecnospeed

### ISSUE THREAD

**Issue by wwwflorencio** [bemugmga/meetups#8]
# 8º  Backend Meetup Group MGA - Tecnospeed

Estamos indo para o oitavoencontro do BEMUGMGA. Vai rolar dia **24/05** à partir das **19h** (vai cair em uma quinta feira).

Contamos com sua participação :D

**Link meetup** https://www.meetup.com/pt-BR/developerparana/events/250811764/

## Votação
Para tornar a votação democrática as palestras aqui submetidas com mais :+1: serão escolhidas para o encontro, porém fica o convite para que você submeta também nos próximos encontros.

Para submeter palestras comente nessa issue seguindo o modelo da issue #2

**Comment by mayconds000** [comment]
## Melhorando seu código php com Paradigma Funcional e Object Calisthenics

#### Nome
Maycon Donizete
#### Grau da palestra

- [ ] Iniciante
- [x] Intermediário
- [ ] Avançado

#### Tempo previsto
00:45h

#### Abstract
Esta palestra tem como objetivo apresentar algumas abordagens de como podemos estar melhorando o nosso código php utilizando alguns conceitos do paradigma funcional e object calisthenics

**Comment by SergioLacerda** [comment]
O dilema da dupla identidade: um robô no serviço e um humano com azia do mundo fora dele.

#### Nome
Sérgio Lacerda
#### Grau da palestra
- [x] Iniciante
- [ ] Intermediário
- [ ] Avançado
#### Tempo previsto
01:30h
#### Abstract
Desanimado com a sua condição atual? com a forma de trabalho vigente?
O que esperar do mercado de TI além do ecossistema maringaense?
Eu realmente quero buscar algo mais?

Embora tudo isso possa soar como "auto-ajuda",
espero demonstrar a perspectiva de um desenvolvedor de sistemas sobre o panorama maringaense, 
e fazer um contra-ponto para superar nossa mediocridade e se aventurar em "aguas mais profundas".

A arma para essa odisséia: uma potência adormecida e atrofiada: a virtude.

**Comment by zonetti** [comment]
## Como fazer um jogo se jogar sozinho utilizando redes neurais e algoritmos genéticos

#### Nome
Osvaldo Zonetti
#### Grau da palestra
- [ ] Iniciante
- [x] Intermediário
- [ ] Avançado
#### Tempo previsto
01:00h
#### Abstract
Desde a primeira vez que vi uma simulação de algoritmos genéticos fiquei maravilhado com a idéia e suas possibilidades.

De lá pra cá venho alimentando minha curiosidade e acompanhando os avanços na área de Machine Learning e AI em geral, até que, recentemente, decidi fazer algo a respeito...

Nesta talk eu compartilho como foi minha jornada, enquanto hobbysta, da curiosidade até o entedimento (razoável) sobre redes neurais e algoritmos genéticos.
