### ISSUE TITLE
9º  Backend Meetup Group MGA - FCV

### ISSUE THREAD

**Issue by wwwflorencio** [bemugmga/meetups#9]
# 9º  Backend Meetup Group MGA - FCV
Estamos indo para o nono encontro do BEMUGMGA. Vai rolar dia **07/06** à partir das **19h** (vai cair em uma quinta feira).

Contamos com sua participação :D

**Link meetup** 
https://www.meetup.com/pt-BR/developerparana/events/251220539/

## Votação
São duas palestras por evento, então para tornar a votação democrática as palestras aqui submetidas com mais :+1: serão escolhidas para o encontro, porém fica o convite para que você submeta também nos próximos encontros.

Para submeter palestras comente nessa issue seguindo o modelo da issue #2

**Comment by DaniloTerra** [comment]
# Clean Architecture com PHP

#### Nome
Danilo
#### Grau da palestra
- [ ] Iniciante
- [x] Intermediário
- [ ] Avançado
#### Tempo previsto
01:00h
#### Abstract
Arquitetar (projetar) uma aplicação é um desafio. Se feito de maneira equivocada, pode te dar muita dor de cabeça no futuro: testes podem se tornar difíceis (ou até impossíveis) e refatorações podem se tornar um pesadelo. Nessa apresentação veremos dicas para deixar nosso código mais testável, fácil de trabalhar e fácil de manter.

**Comment by andrevandal** [comment]
## Comunicatividade e Técnicas de Negociação:
### O segredo para negociar com sucesso

#### Nome
André Van Dal
#### Grau da palestra
{Marque com um X o nível da palestra}
- [x] Iniciante
- [x] Intermediário
- [ ] Avançado
#### Tempo previsto
1h45min
#### Abstract
Na área de desenvolvimento, muitos colaborares não tem habilidades comunicativas: seja para se expor ou se posicionar e até sobre como negociar a si mesmo na hora de se aplicar a um novo desafio. Nessa apresentação, tentarei ser um pouco mais interativo com os participantes para levá-los a iniciar o desafio de se tornar uma pessoa mais comunicativa e de conseguir coragem e ânimo para se expor e negociar com sucesso.
Tudo isso partindo de uma pessoa ex-tímida até o patamar de pessoa que fala mais do que a própria língua (eu, no caso) e trabalha com isso atualmente.
